[project]
name = "numcodecs-combinators"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numcodecs~=0.13",
    "numpy~=2.2",
]
